### ISSUE TITLE
config.json not found

### ISSUE THREAD

**Issue by bitsnaps** [alger-ia/dziribert#1]
Salam team,

Just went through the example, I got this error:
```
HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/dziribert/resolve/main/config.json
```
Looks like the link to the [config.json](https://huggingface.co/alger-ia/dziribert/raw/main/config.json) file has changed?
P.S. I've tried this demo in colab/gitpod and got the same error message.

Regards

**Comment by amineabdaoui** [comment]
Salam Ibrahim, 

Are you getting this error when calling the `from_pretrained()` method ?

I just tried the following code on colab now using transformers 4.5.1 and everything went well:
![capture-dziribert-download](https://user-images.githubusercontent.com/17952908/135731166-d2557b07-35ff-45fd-9095-6901e56920d9.png)
l:

**Comment by bitsnaps** [comment]
W/Salam Amine,

These methods are working fine, I got that error when calling `pipeline` function
<img width="890" alt="error" src="https://user-images.githubusercontent.com/1217741/135743002-07091042-8714-4dbf-87b7-4f1c590c11c4.png">
.

**Comment by ghost** [comment]
https://huggingface.co/alger-ia/dziribert/blob/main/config.json
the error is showing a wrong link ?

**Comment by amineabdaoui** [comment]
W/Salam,
If the model and tokenizer are already loaded then you just need to pass the variables to the pipeline:
```
fill_mask = pipeline(
    "fill-mask",
    model=model,
    tokenizer=tokenizer
)
```

Otherwise, you can also download and load them directly inside the pipeline using:
```
fill_mask = pipeline(
    "fill-mask",
    model="alger-ia/dziribert",
    tokenizer="alger-ia/dziribert"
)
```

**Comment by amineabdaoui** [comment]
I added the organization in the [run_lm.py](https://github.com/alger-ia/dziribert/blob/main/run_lm.py) script.

**Comment by bitsnaps** [comment]
Great! it works.
Thanks!
